using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage;
using SmartCard.Data;
using SmartCard.Models;

namespace SmartCard.Extensions
{
    public static class ApplicationExtensions
    {
        public static async Task UseDatabaseInitializer(this IApplicationBuilder app)
        {
            using (var scope = app.ApplicationServices.CreateScope())
            {
                var context = scope.ServiceProvider.GetRequiredService<ApplicationDbContext>();
                var userManager = scope.ServiceProvider.GetRequiredService<UserManager<ApplicationUser>>();
                var roleManager = scope.ServiceProvider.GetRequiredService<RoleManager<IdentityRole>>();
                var loggerFactory = scope.ServiceProvider.GetService<ILoggerFactory>();
                var logger = loggerFactory?.CreateLogger("DatabaseInitializer");

                try
                {
                    logger?.LogInformation("Ensuring database tables exist...");
                    
                    // Check if AspNetRoles table exists by checking system catalogs
                    var script = context.Database.GenerateCreateScript();
                    
                    // If running on PostgreSQL
                    if (context.Database.IsNpgsql())
                    {
                        var createTablesSql = @"
                            CREATE TABLE IF NOT EXISTS ""AspNetRoles"" (
                                ""Id"" text NOT NULL PRIMARY KEY,
                                ""Name"" character varying(256) NULL,
                                ""NormalizedName"" character varying(256) NULL,
                                ""ConcurrencyStamp"" text NULL
                            );
                            CREATE UNIQUE INDEX IF NOT EXISTS ""RoleNameIndex"" ON ""AspNetRoles"" (""NormalizedName"") WHERE ""NormalizedName"" IS NOT NULL;

                            CREATE TABLE IF NOT EXISTS ""AspNetUsers"" (
                                ""Id"" text NOT NULL PRIMARY KEY,
                                ""FirstName"" character varying(100) NULL,
                                ""LastName"" character varying(100) NULL,
                                ""CreatedDate"" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                ""LastLoginDate"" timestamp with time zone NULL,
                                ""UserName"" character varying(256) NULL,
                                ""NormalizedUserName"" character varying(256) NULL,
                                ""Email"" character varying(256) NULL,
                                ""NormalizedEmail"" character varying(256) NULL,
                                ""EmailConfirmed"" boolean NOT NULL,
                                ""PasswordHash"" text NULL,
                                ""SecurityStamp"" text NULL,
                                ""ConcurrencyStamp"" text NULL,
                                ""PhoneNumber"" text NULL,
                                ""PhoneNumberConfirmed"" boolean NOT NULL,
                                ""TwoFactorEnabled"" boolean NOT NULL,
                                ""LockoutEnd"" timestamp with time zone NULL,
                                ""LockoutEnabled"" boolean NOT NULL,
                                ""AccessFailedCount"" integer NOT NULL
                            );
                            CREATE INDEX IF NOT EXISTS ""EmailIndex"" ON ""AspNetUsers"" (""NormalizedEmail"");
                            CREATE UNIQUE INDEX IF NOT EXISTS ""UserNameIndex"" ON ""AspNetUsers"" (""NormalizedUserName"") WHERE ""NormalizedUserName"" IS NOT NULL;

                            CREATE TABLE IF NOT EXISTS ""AspNetRoleClaims"" (
                                ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                ""RoleId"" text NOT NULL REFERENCES ""AspNetRoles"" (""Id"") ON DELETE CASCADE,
                                ""ClaimType"" text NULL,
                                ""ClaimValue"" text NULL
                            );

                            CREATE TABLE IF NOT EXISTS ""AspNetUserClaims"" (
                                ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                ""UserId"" text NOT NULL REFERENCES ""AspNetUsers"" (""Id"") ON DELETE CASCADE,
                                ""ClaimType"" text NULL,
                                ""ClaimValue"" text NULL
                            );

                            CREATE TABLE IF NOT EXISTS ""AspNetUserLogins"" (
                                ""LoginProvider"" text NOT NULL,
                                ""ProviderKey"" text NOT NULL,
                                ""ProviderDisplayName"" text NULL,
                                ""UserId"" text NOT NULL REFERENCES ""AspNetUsers"" (""Id"") ON DELETE CASCADE,
                                PRIMARY KEY (""LoginProvider"", ""ProviderKey"")
                            );

                            CREATE TABLE IF NOT EXISTS ""AspNetUserRoles"" (
                                ""UserId"" text NOT NULL REFERENCES ""AspNetUsers"" (""Id"") ON DELETE CASCADE,
                                ""RoleId"" text NOT NULL REFERENCES ""AspNetRoles"" (""Id"") ON DELETE CASCADE,
                                PRIMARY KEY (""UserId"", ""RoleId"")
                            );

                            CREATE TABLE IF NOT EXISTS ""AspNetUserTokens"" (
                                ""UserId"" text NOT NULL REFERENCES ""AspNetUsers"" (""Id"") ON DELETE CASCADE,
                                ""LoginProvider"" text NOT NULL,
                                ""Name"" text NOT NULL,
                                ""Value"" text NULL,
                                PRIMARY KEY (""UserId"", ""LoginProvider"", ""Name"")
                            );

                            CREATE TABLE IF NOT EXISTS ""Departments"" (
                                ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                ""Name"" character varying(100) NOT NULL,
                                ""CreatedDate"" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                ""UpdatedDate"" timestamp with time zone NULL,
                                ""IsActive"" boolean NOT NULL DEFAULT TRUE
                            );

                            CREATE TABLE IF NOT EXISTS ""Employees"" (
                                ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                ""EmployeeNumber"" character varying(50) NOT NULL,
                                ""FirstName"" character varying(100) NOT NULL,
                                ""LastName"" character varying(100) NOT NULL,
                                ""Email"" character varying(100) NULL,
                                ""MonthlyFuelQuota"" numeric(10,2) NOT NULL DEFAULT 0,
                                ""IsActive"" boolean NOT NULL DEFAULT TRUE,
                                ""CreatedDate"" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                ""UpdatedDate"" timestamp with time zone NULL,
                                ""DepartmentId"" integer NULL REFERENCES ""Departments"" (""Id"") ON DELETE SET NULL
                            );
                            CREATE UNIQUE INDEX IF NOT EXISTS ""IX_Employees_EmployeeNumber"" ON ""Employees"" (""EmployeeNumber"");

                            CREATE TABLE IF NOT EXISTS ""Cards"" (
                                ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                ""CardNumber"" character varying(50) NOT NULL,
                                ""Status"" integer NOT NULL DEFAULT 0,
                                ""CreatedDate"" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                ""UpdatedDate"" timestamp with time zone NULL,
                                ""LastUsedDate"" timestamp with time zone NULL,
                                ""EmployeeId"" integer NULL REFERENCES ""Employees"" (""Id"") ON DELETE SET NULL
                            );
                            CREATE UNIQUE INDEX IF NOT EXISTS ""IX_Cards_CardNumber"" ON ""Cards"" (""CardNumber"");

                            CREATE TABLE IF NOT EXISTS ""FuelQuotas"" (
                                ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                ""EmployeeId"" integer NOT NULL REFERENCES ""Employees"" (""Id"") ON DELETE CASCADE,
                                ""Month"" integer NOT NULL,
                                ""Year"" integer NOT NULL,
                                ""QuotaInLiters"" numeric(10,2) NOT NULL,
                                ""UsedLiters"" numeric(10,2) NOT NULL DEFAULT 0,
                                ""CreatedDate"" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                ""UpdatedDate"" timestamp with time zone NULL
                            );
                            CREATE UNIQUE INDEX IF NOT EXISTS ""IX_FuelQuotas_EmployeeId_Month_Year"" ON ""FuelQuotas"" (""EmployeeId"", ""Month"", ""Year"");

                            CREATE TABLE IF NOT EXISTS ""Consumptions"" (
                                ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                ""CardId"" integer NOT NULL REFERENCES ""Cards"" (""Id"") ON DELETE NO ACTION,
                                ""EmployeeId"" integer NOT NULL REFERENCES ""Employees"" (""Id"") ON DELETE NO ACTION,
                                ""AmountInLiters"" numeric(10,2) NOT NULL,
                                ""TransactionDate"" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                ""Description"" character varying(200) NULL,
                                ""CreatedDate"" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
                            );

                            CREATE TABLE IF NOT EXISTS ""CompanyFuelSupplies"" (
                                ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                ""QuantityInLiters"" numeric(10,2) NOT NULL,
                                ""SupplyDate"" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                ""Supplier"" character varying(100) NULL,
                                ""ReferenceNumber"" character varying(100) NULL,
                                ""Notes"" character varying(500) NULL,
                                ""CreatedBy"" character varying(100) NULL,
                                ""CreatedDate"" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
                            );
                        ";

                        await context.Database.ExecuteSqlRawAsync(createTablesSql);
                    }
                    else
                    {
                        var databaseCreator = context.Database.GetService<Microsoft.EntityFrameworkCore.Storage.IRelationalDatabaseCreator>();
                        if (!databaseCreator.Exists())
                        {
                            await databaseCreator.CreateAsync();
                        }
                        if (!databaseCreator.HasTables())
                        {
                            await databaseCreator.CreateTablesAsync();
                        }
                    }

                    logger?.LogInformation("Database tables ready. Seeding default roles and admin...");

                    // Create default roles
                    await CreateDefaultRolesAsync(roleManager, userManager);

                    // Create default admin user if it doesn't exist
                    await CreateDefaultAdminUserAsync(userManager, roleManager);

                    logger?.LogInformation("Database initialization completed successfully.");
                }
                catch (Exception ex)
                {
                    logger?.LogError(ex, "Error during database initialization: {Message}", ex.Message);
                    // Let the application continue running or rethrow if critical
                    throw;
                }
            }
        }

        private static async Task CreateDefaultRolesAsync(RoleManager<IdentityRole> roleManager, UserManager<ApplicationUser> userManager)
        {
            // Liste des rôles cibles
            var targetRoles = new[] { "Admin", "Pompiste", "Employé" };

            // 1. S'assurer que les nouveaux rôles existent
            foreach (var roleName in targetRoles)
            {
                if (!await roleManager.RoleExistsAsync(roleName))
                {
                    await roleManager.CreateAsync(new IdentityRole(roleName));
                }
            }

            // 2. Migrer les utilisateurs des anciens rôles et les supprimer
            var migrationMap = new Dictionary<string, string>
            {
                { "PumpAttendant", "Pompiste" },
                { "Employee", "Employé" }
            };

            foreach (var mapping in migrationMap)
            {
                var oldRoleName = mapping.Key;
                var newRoleName = mapping.Value;

                var oldRole = await roleManager.FindByNameAsync(oldRoleName);
                if (oldRole != null)
                {
                    // Récupérer tous les utilisateurs ayant l'ancien rôle
                    var usersInOldRole = await userManager.GetUsersInRoleAsync(oldRoleName);
                    foreach (var user in usersInOldRole)
                    {
                        // Ajouter le nouveau rôle s'ils ne l'ont pas déjà
                        if (!await userManager.IsInRoleAsync(user, newRoleName))
                        {
                            await userManager.AddToRoleAsync(user, newRoleName);
                        }
                        // Retirer l'ancien rôle
                        await userManager.RemoveFromRoleAsync(user, oldRoleName);
                    }

                    // Supprimer l'ancien rôle de la base de données
                    await roleManager.DeleteAsync(oldRole);
                }
            }
        }

        private static async Task CreateDefaultAdminUserAsync(UserManager<ApplicationUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            var adminEmail = "admin@smartcard.com";
            var adminUser = await userManager.FindByEmailAsync(adminEmail);

            if (adminUser == null)
            {
                adminUser = new ApplicationUser
                {
                    UserName = adminEmail,
                    Email = adminEmail,
                    FirstName = "System",
                    LastName = "Administrator"
                };

                var result = await userManager.CreateAsync(adminUser, "Admin123!");

                if (result.Succeeded)
                {
                    await userManager.AddToRoleAsync(adminUser, "Admin");
                }
            }
        }
    }
}